export const aslSigns = [
  // Alphabet
  { sign: "A", emoji: "🅰️", description: "Fist with thumb on the side", category: "alphabet" },
  { sign: "B", emoji: "🅱️", description: "Open hand, fingers together, thumb tucked in", category: "alphabet" },
  { sign: "C", emoji: "🇨", description: "Hand curved into a 'C' shape", category: "alphabet" },
  { sign: "D", emoji: "🇩", description: "Index finger up, others touching thumb", category: "alphabet" },
  { sign: "E", emoji: "🇪", description: "Fingers curled, thumb tucked under", category: "alphabet" },
  { sign: "F", emoji: "🇫", description: "Index and thumb touch, others up (OK sign)", category: "alphabet" },
  { sign: "G", emoji: "🇬", description: "Index and thumb pointing sideways", category: "alphabet" },
  { sign: "H", emoji: "🇭", description: "Index and middle pointing sideways", category: "alphabet" },
  { sign: "I", emoji: "🇮", description: "Pinky finger up", category: "alphabet" },
  { sign: "J", emoji: "🇯", description: "Pinky finger up, drawing a 'J' curve", category: "alphabet" },
  { sign: "K", emoji: "🇰", description: "Index and middle up (V), thumb on middle", category: "alphabet" },
  { sign: "L", emoji: "🇱", description: "Index and thumb forming an 'L'", category: "alphabet" },
  { sign: "M", emoji: "🇲", description: "Thumb tucked under three fingers", category: "alphabet" },
  { sign: "N", emoji: "🇳", description: "Thumb tucked under two fingers", category: "alphabet" },
  { sign: "O", emoji: "🅾️", description: "Fingers touching thumb in a circle", category: "alphabet" },
  { sign: "P", emoji: "🇵", description: "Like 'K' but pointing downwards", category: "alphabet" },
  { sign: "Q", emoji: "🇶", description: "Like 'G' but pointing downwards", category: "alphabet" },
  { sign: "R", emoji: "🇷", description: "Index and middle fingers crossed", category: "alphabet" },
  { sign: "S", emoji: "🇸", description: "Fist with thumb over fingers", category: "alphabet" },
  { sign: "T", emoji: "🇹", description: "Thumb tucked under index finger", category: "alphabet" },
  { sign: "U", emoji: "🇺", description: "Index and middle fingers up and together", category: "alphabet" },
  { sign: "V", emoji: "🇻", description: "Index and middle fingers up and apart", category: "alphabet" },
  { sign: "W", emoji: "🇼", description: "Index, middle, and ring fingers up", category: "alphabet" },
  { sign: "X", emoji: "🇽", description: "Index finger hooked", category: "alphabet" },
  { sign: "Y", emoji: "🇾", description: "Thumb and pinky extended", category: "alphabet" },
  { sign: "Z", emoji: "🇿", description: "Index finger drawing a 'Z' in the air", category: "alphabet" },
  
  // Numbers
  { sign: "0", emoji: "0️⃣", description: "Fingers touching thumb in a circle", category: "number" },
  { sign: "1", emoji: "1️⃣", description: "Index finger up", category: "number" },
  { sign: "2", emoji: "2️⃣", description: "Index and middle fingers up", category: "number" },
  { sign: "3", emoji: "3️⃣", description: "Thumb, index, and middle fingers up", category: "number" },
  { sign: "4", emoji: "4️⃣", description: "Four fingers up, thumb tucked", category: "number" },
  { sign: "5", emoji: "5️⃣", description: "All five fingers extended", category: "number" },
  { sign: "6", emoji: "6️⃣", description: "Thumb and pinky touching", category: "number" },
  { sign: "7", emoji: "7️⃣", description: "Thumb and ring finger touching", category: "number" },
  { sign: "8", emoji: "8️⃣", description: "Thumb and middle finger touching", category: "number" },
  { sign: "9", emoji: "9️⃣", description: "Thumb and index finger touching", category: "number" },

  // Common Expressions
  { sign: "I Love You", emoji: "🤟", description: "Thumb, index, and pinky extended", category: "expression" },
  { sign: "Thumbs Up", emoji: "👍", description: "Thumb up, fingers closed", category: "response" },
];

export const islSigns = [
  // Alphabet (ISL is typically two-handed)
  { sign: "A", emoji: "🅰️", description: "Right index finger touches left thumb tip", category: "alphabet" },
  { sign: "B", emoji: "🅱️", description: "Both hands open, palms facing each other", category: "alphabet" },
  { sign: "C", emoji: "🇨", description: "Right hand curved into a 'C' shape", category: "alphabet" },
  { sign: "D", emoji: "🇩", description: "Right index finger touches left index finger tip", category: "alphabet" },
  { sign: "E", emoji: "🇪", description: "Right index finger touches left index finger middle joint", category: "alphabet" },
  { sign: "F", emoji: "🇫", description: "Right index and middle fingers placed across left index finger", category: "alphabet" },
  { sign: "G", emoji: "🇬", description: "Both fists together, one on top of the other", category: "alphabet" },
  { sign: "H", emoji: "🇭", description: "Right palm slides across left palm", category: "alphabet" },
  { sign: "I", emoji: "🇮", description: "Right index finger touches left middle finger tip", category: "alphabet" },
  { sign: "J", emoji: "🇯", description: "Right index finger draws a 'J' on left palm", category: "alphabet" },
  { sign: "K", emoji: "🇰", description: "Right index finger hooked on left index finger", category: "alphabet" },
  { sign: "L", emoji: "🇱", description: "Right index finger placed on left palm in 'L' shape", category: "alphabet" },
  { sign: "M", emoji: "🇲", description: "Right three fingers placed on left palm", category: "alphabet" },
  { sign: "N", emoji: "🇳", description: "Right two fingers placed on left palm", category: "alphabet" },
  { sign: "O", emoji: "🅾️", description: "Right index finger touches left ring finger tip", category: "alphabet" },
  { sign: "P", emoji: "🇵", description: "Right index and thumb form a circle on left index finger", category: "alphabet" },
  { sign: "Q", emoji: "🇶", description: "Right hand hooked around left thumb", category: "alphabet" },
  { sign: "R", emoji: "🇷", description: "Right index finger curled on left palm", category: "alphabet" },
  { sign: "S", emoji: "🇸", description: "Right pinky finger hooked on left pinky finger", category: "alphabet" },
  { sign: "T", emoji: "🇹", description: "Right index finger touches left pinky finger tip", category: "alphabet" },
  { sign: "U", emoji: "🇺", description: "Right index finger touches left pinky finger base", category: "alphabet" },
  { sign: "V", emoji: "🇻", description: "Right index and middle fingers form a 'V' on left palm", category: "alphabet" },
  { sign: "W", emoji: "🇼", description: "Both hands' fingers interlocked", category: "alphabet" },
  { sign: "X", emoji: "🇽", description: "Both index fingers crossed", category: "alphabet" },
  { sign: "Y", emoji: "🇾", description: "Right index finger placed in the 'V' between left thumb and index", category: "alphabet" },
  { sign: "Z", emoji: "🇿", description: "Right palm placed against left palm, fingers pointing in opposite directions", category: "alphabet" },

  // Numbers (1-9 from your dataset)
  { sign: "1", emoji: "1️⃣", description: "ISL Number 1: Index finger up", category: "number" },
  { sign: "2", emoji: "2️⃣", description: "ISL Number 2: Index and middle fingers up", category: "number" },
  { sign: "3", emoji: "3️⃣", description: "ISL Number 3: Index, middle, and ring fingers up", category: "number" },
  { sign: "4", emoji: "4️⃣", description: "ISL Number 4: Four fingers up", category: "number" },
  { sign: "5", emoji: "5️⃣", description: "ISL Number 5: All five fingers up", category: "number" },
  { sign: "6", emoji: "6️⃣", description: "ISL Number 6: Thumb and index of both hands touching", category: "number" },
  { sign: "7", emoji: "7️⃣", description: "ISL Number 7: Right index touching left palm", category: "number" },
  { sign: "8", emoji: "8️⃣", description: "ISL Number 8: Right middle touching left palm", category: "number" },
  { sign: "9", emoji: "9️⃣", description: "ISL Number 9: Right ring touching left palm", category: "number" },

  // Common Greetings & Responses
  { sign: "Hello", emoji: "👋", description: "Hand wave or Namaste gesture", category: "greeting" },
  { sign: "Thank You", emoji: "🙏", description: "Both palms together (Namaste)", category: "greeting" },
  { sign: "Yes", emoji: "👍", description: "Thumb up", category: "response" },
  { sign: "No", emoji: "👎", description: "Thumb down", category: "response" },
];
